require("dotenv").config();
const { CosmosClient } = require("@azure/cosmos");

const databaseId = process.env.COSMOS_DATABASE_ID || "roadsos";
const servicesContainer = process.env.COSMOS_SERVICES_CONTAINER || "emergency_services";
const incidentsContainer = process.env.COSMOS_INCIDENTS_CONTAINER || "incidents";
const verified = "2026-05-01T00:00:00.000Z";

const services = [
  { id: "za-jhb-chris-hani-baragwanath", name: "Chris Hani Baragwanath Academic Hospital", service_type: "trauma_centre", latitude: -26.2617, longitude: 27.9394, address: "Diepkloof, Soweto", city: "Johannesburg", country_code: "ZA", phone_numbers: ["+27119338000", "112"], is_24_hours: true, rating: 4.1, capacity: 3200, free_beds: 280, services_offered: ["trauma", "emergency", "surgery"], languages: ["en", "zu", "st"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "za-jhb-charlotte-maxeke", name: "Charlotte Maxeke Johannesburg Academic Hospital", service_type: "trauma_centre", latitude: -26.1751, longitude: 28.0442, city: "Johannesburg", country_code: "ZA", phone_numbers: ["+27114882111", "112"], is_24_hours: true, rating: 4.0, capacity: 1088, free_beds: 90, services_offered: ["trauma", "emergency"], languages: ["en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "za-jhb-netcare-911", name: "Netcare 911 Johannesburg", service_type: "ambulance", latitude: -26.1047, longitude: 28.0567, city: "Johannesburg", country_code: "ZA", phone_numbers: ["082911", "112"], is_24_hours: true, rating: 4.5, services_offered: ["advanced life support"], languages: ["en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "za-jhb-er24", name: "ER24 Johannesburg", service_type: "ambulance", latitude: -26.1438, longitude: 28.0436, city: "Johannesburg", country_code: "ZA", phone_numbers: ["084124", "112"], is_24_hours: true, rating: 4.4, services_offered: ["ambulance", "medical rescue"], languages: ["en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "za-jhb-saps-central", name: "Johannesburg Central Police Station", service_type: "police", latitude: -26.2044, longitude: 28.0456, city: "Johannesburg", country_code: "ZA", phone_numbers: ["10111", "+27114976000"], is_24_hours: true, rating: 3.5, services_offered: ["police"], languages: ["en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "za-jhb-sanbs", name: "SANBS Johannesburg Donor Centre", service_type: "blood_bank", latitude: -26.1846, longitude: 28.0196, city: "Johannesburg", country_code: "ZA", phone_numbers: ["0800119031"], is_24_hours: false, open_now: true, rating: 4.4, capacity: 500, free_beds: 310, services_offered: ["blood"], languages: ["en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "za-cpt-groote-schuur", name: "Groote Schuur Hospital", service_type: "trauma_centre", latitude: -33.9416, longitude: 18.4633, city: "Cape Town", country_code: "ZA", phone_numbers: ["+27214049111", "112"], is_24_hours: true, rating: 4.2, capacity: 893, free_beds: 80, services_offered: ["trauma", "emergency"], languages: ["en", "af"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "za-cpt-tygerberg", name: "Tygerberg Hospital", service_type: "trauma_centre", latitude: -33.9127, longitude: 18.6117, city: "Cape Town", country_code: "ZA", phone_numbers: ["+27219385555"], is_24_hours: true, rating: 4.0, capacity: 1384, free_beds: 130, services_offered: ["trauma", "emergency"], languages: ["en", "af"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "za-cpt-saps-central", name: "Cape Town Central Police Station", service_type: "police", latitude: -33.9253, longitude: 18.4239, city: "Cape Town", country_code: "ZA", phone_numbers: ["10111", "+27214678000"], is_24_hours: true, rating: 3.6, services_offered: ["police"], languages: ["en", "af"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "za-dbn-addington", name: "Addington Hospital", service_type: "hospital", latitude: -29.8587, longitude: 31.0398, city: "Durban", country_code: "ZA", phone_numbers: ["+27313272000"], is_24_hours: true, rating: 3.8, capacity: 571, free_beds: 44, services_offered: ["emergency"], languages: ["en", "zu"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "za-dbn-saps-central", name: "Durban Central Police Station", service_type: "police", latitude: -29.8569, longitude: 31.0292, city: "Durban", country_code: "ZA", phone_numbers: ["10111", "+27313251111"], is_24_hours: true, rating: 3.6, services_offered: ["police"], languages: ["en", "zu"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "za-dbn-tyre", name: "Tiger Wheel & Tyre Durban", service_type: "tyre_shop", latitude: -29.8312, longitude: 31.0189, city: "Durban", country_code: "ZA", phone_numbers: ["+27313034757"], is_24_hours: false, open_now: true, rating: 4.2, services_offered: ["tyres", "puncture repair"], languages: ["en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "in-delhi-aiims", name: "AIIMS Delhi Trauma Centre", service_type: "trauma_centre", latitude: 28.5672, longitude: 77.2100, city: "Delhi", country_code: "IN", phone_numbers: ["+911126588500", "108"], is_24_hours: true, rating: 4.6, capacity: 2478, free_beds: 180, services_offered: ["trauma", "emergency"], languages: ["hi", "en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "in-delhi-rml", name: "Dr. Ram Manohar Lohia Hospital", service_type: "hospital", latitude: 28.6251, longitude: 77.2005, city: "Delhi", country_code: "IN", phone_numbers: ["+911123404304", "108"], is_24_hours: true, rating: 4.1, capacity: 1532, free_beds: 120, services_offered: ["emergency"], languages: ["hi", "en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "in-delhi-police", name: "Delhi Police Emergency", service_type: "police", latitude: 28.6170, longitude: 77.2080, city: "Delhi", country_code: "IN", phone_numbers: ["100", "112"], is_24_hours: true, rating: 4.0, services_offered: ["police"], languages: ["hi", "en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "in-delhi-cats", name: "CATS 108 Ambulance Delhi", service_type: "ambulance", latitude: 28.6139, longitude: 77.2090, city: "Delhi", country_code: "IN", phone_numbers: ["108", "102"], is_24_hours: true, rating: 4.1, services_offered: ["ambulance"], languages: ["hi", "en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "in-mumbai-kem", name: "KEM Hospital Mumbai", service_type: "trauma_centre", latitude: 19.0017, longitude: 72.8424, city: "Mumbai", country_code: "IN", phone_numbers: ["+912224107000", "108"], is_24_hours: true, rating: 4.2, capacity: 1800, free_beds: 150, services_offered: ["trauma", "emergency"], languages: ["mr", "hi", "en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "in-mumbai-sion", name: "Lokmanya Tilak Municipal General Hospital", service_type: "trauma_centre", latitude: 19.0375, longitude: 72.8610, city: "Mumbai", country_code: "IN", phone_numbers: ["+912224073638", "108"], is_24_hours: true, rating: 4.0, capacity: 1400, free_beds: 110, services_offered: ["trauma"], languages: ["mr", "hi", "en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "in-mumbai-police", name: "Mumbai Police Emergency", service_type: "police", latitude: 18.9388, longitude: 72.8354, city: "Mumbai", country_code: "IN", phone_numbers: ["100", "112"], is_24_hours: true, rating: 4.1, services_offered: ["police"], languages: ["mr", "hi", "en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "in-chennai-gh", name: "Rajiv Gandhi Government General Hospital", service_type: "trauma_centre", latitude: 13.0820, longitude: 80.2750, city: "Chennai", country_code: "IN", phone_numbers: ["+914425305000", "108"], is_24_hours: true, rating: 4.1, capacity: 2722, free_beds: 190, services_offered: ["trauma", "emergency"], languages: ["ta", "en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "in-chennai-apollo", name: "Apollo Hospitals Greams Road", service_type: "hospital", latitude: 13.0635, longitude: 80.2517, city: "Chennai", country_code: "IN", phone_numbers: ["+914428290200", "1066"], is_24_hours: true, rating: 4.4, capacity: 560, free_beds: 40, services_offered: ["emergency"], languages: ["ta", "en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "in-chennai-police", name: "Chennai Police Emergency", service_type: "police", latitude: 13.0827, longitude: 80.2707, city: "Chennai", country_code: "IN", phone_numbers: ["100", "112"], is_24_hours: true, rating: 4.0, services_offered: ["police"], languages: ["ta", "en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "uk-london-royal-london", name: "The Royal London Hospital Major Trauma Centre", service_type: "trauma_centre", latitude: 51.5189, longitude: -0.0597, city: "London", country_code: "UK", phone_numbers: ["999", "+442073777000"], is_24_hours: true, rating: 4.2, capacity: 845, free_beds: 70, services_offered: ["major trauma", "emergency"], languages: ["en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "uk-london-st-marys", name: "St Mary's Hospital Major Trauma Centre", service_type: "trauma_centre", latitude: 51.5174, longitude: -0.1731, city: "London", country_code: "UK", phone_numbers: ["999", "+442033121234"], is_24_hours: true, rating: 4.0, capacity: 495, free_beds: 38, services_offered: ["major trauma", "emergency"], languages: ["en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "uk-london-ambulance", name: "London Ambulance Service", service_type: "ambulance", latitude: 51.5072, longitude: -0.1276, city: "London", country_code: "UK", phone_numbers: ["999", "112"], is_24_hours: true, rating: 4.0, services_offered: ["ambulance"], languages: ["en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "uk-london-met-police", name: "Metropolitan Police Emergency", service_type: "police", latitude: 51.5020, longitude: -0.1246, city: "London", country_code: "UK", phone_numbers: ["999", "101"], is_24_hours: true, rating: 3.9, services_offered: ["police"], languages: ["en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "uk-london-nhsbt", name: "NHS Blood and Transplant London", service_type: "blood_bank", latitude: 51.5229, longitude: -0.1116, city: "London", country_code: "UK", phone_numbers: ["03001232323"], is_24_hours: false, open_now: true, rating: 4.4, capacity: 800, free_beds: 540, services_offered: ["blood"], languages: ["en"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "us-nyc-bellevue", name: "Bellevue Hospital Center Level I Trauma", service_type: "trauma_centre", latitude: 40.7394, longitude: -73.9767, city: "New York", country_code: "US", phone_numbers: ["911", "+12125625000"], is_24_hours: true, rating: 4.1, capacity: 844, free_beds: 62, services_offered: ["level 1 trauma", "emergency"], languages: ["en", "es"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "us-nyc-mount-sinai", name: "Mount Sinai Morningside Emergency Department", service_type: "hospital", latitude: 40.8053, longitude: -73.9603, city: "New York", country_code: "US", phone_numbers: ["911", "+12125235000"], is_24_hours: true, rating: 4.0, capacity: 495, free_beds: 32, services_offered: ["emergency"], languages: ["en", "es"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "us-nyc-ems", name: "FDNY EMS New York", service_type: "ambulance", latitude: 40.7128, longitude: -74.0060, city: "New York", country_code: "US", phone_numbers: ["911"], is_24_hours: true, rating: 4.3, services_offered: ["ambulance", "rescue"], languages: ["en", "es"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "us-nyc-nypd", name: "NYPD Emergency", service_type: "police", latitude: 40.7127, longitude: -74.0059, city: "New York", country_code: "US", phone_numbers: ["911", "311"], is_24_hours: true, rating: 3.9, services_offered: ["police"], languages: ["en", "es"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "us-nyc-red-cross", name: "American Red Cross Greater New York", service_type: "blood_bank", latitude: 40.7410, longitude: -73.9901, city: "New York", country_code: "US", phone_numbers: ["18007332767"], is_24_hours: false, open_now: true, rating: 4.4, capacity: 1000, free_beds: 720, services_offered: ["blood", "disaster response"], languages: ["en", "es"], last_verified_at: verified, is_active: true, source: "seed" },
  { id: "us-nyc-towing", name: "NYC Auto Towing Service", service_type: "towing", latitude: 40.7473, longitude: -73.9857, city: "New York", country_code: "US", phone_numbers: ["+12127361000"], is_24_hours: true, rating: 4.0, services_offered: ["towing", "recovery"], languages: ["en"], last_verified_at: verified, is_active: true, source: "seed" }
];

const incidents = [
  { id: "demo-nyc-1", latitude: 40.739, longitude: -73.977, severity: "HIGH", description: "Demo crash cluster", reported_at: verified, status: "closed", user_id: "seed", country_code: "US", address_approx: "Manhattan", involved_services: [] },
  { id: "demo-delhi-1", latitude: 28.567, longitude: 77.21, severity: "CRITICAL", description: "Demo crash cluster", reported_at: verified, status: "closed", user_id: "seed", country_code: "IN", address_approx: "AIIMS flyover", involved_services: [] }
];

async function main() {
  const client = new CosmosClient({ endpoint: process.env.COSMOS_ENDPOINT, key: process.env.COSMOS_KEY });
  const { database } = await client.databases.createIfNotExists({ id: databaseId });
  const { container: serviceContainer } = await database.containers.createIfNotExists({ id: servicesContainer, partitionKey: { paths: ["/country_code"] } });
  const { container: incidentContainer } = await database.containers.createIfNotExists({ id: incidentsContainer, partitionKey: { paths: ["/country_code"] } });

  for (const service of services) await serviceContainer.items.upsert(service);
  for (const incident of incidents) await incidentContainer.items.upsert(incident);
  console.log(`Seeded ${services.length} emergency services and ${incidents.length} incidents.`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});

module.exports = { services, incidents };
